sudo: required

language: cpp

compiler:
  - g++

services:
  - docker

before_install:
  - docker run -dit --name builder ubuntu:17.10
  - docker exec builder apt-get update
  - docker exec builder apt-get install graphicsmagick
  - docker exec builder apt-get install qt5-default

script: docker exec builder "bash -c ./build.sh"
